### ISSUE TITLE
How to execute code

### ISSUE THREAD

**Issue by yutang814** [takh04/QCNN#3]
How can I implement the training quantum circuit, what are the places that need to be modified in the code, thank you

**Comment by houdong45** [comment]
你好能加好友交流一下嘛

**Comment by houdong45** [comment]
vx：real_hg

**Comment by takh04** [comment]
Hi. Sorry about the late response. I've been busy lately. I will update more detailed Readme file later. 

If you want to train quantum circuits, you can run  _**result.py**_  with desired parameters (unitary Ansatz, encoding methods etc.). It will benchmark the training result and save it as _**result.txt**_  in result folder.

**Comment by yutang814** [comment]
Thank you, by the way, I would like to ask the reason and limitation that only binary classification can be used in the paper, and multi-classification cannot be performed.
Thanks!

> Tak Hur ***@***.***> 於 2022年3月22日 上午1:40 寫道：
> 
> ﻿
> Hi. Sorry about the late response. I've been busy lately. I will update more detailed Readme file later.
> 
> If you want to train quantum circuits, you can run result.py with desired parameters (unitary Ansatz, encoding methods etc.). It will benchmark the training result and save it as result.txt in result folder.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
------ By mail1.ncnu.edu.tw <https://www.ncnu.edu.tw> 
------------------------------------*!!!方便快速的電子郵件仍無法免除延遲或遺失, 
重要或具時效之訊息請勿以電子郵件為唯一傳達方式!!!*
請尊重智慧財產權! 請勿開啟不明來源郵件!
請使用公務信箱收發公務所需資訊,  以免資訊外洩!

-- 
------ By mail1.ncnu.edu.tw <https://www.ncnu.edu.tw> 
------------------------------------*!!!方便快速的電子郵件仍無法免除延遲或遺失, 
重要或具時效之訊息請勿以電子郵件為唯一傳達方式!!!*
請尊重智慧財產權! 請勿開啟不明來源郵件!
請使用公務信箱收發公務所需資訊,  以免資訊外洩!

**Comment by takh04** [comment]
Yes. Multi-classifier can be generated by repeating binary classification. Or maybe you can construct more direct multi-classifier from parameterised quantum circuit, but we haven't tried implementing it. 

The purpose of this work was to compare various parameters (unitary ansatz, data encoding etc). So we used the simplest model, which is binary classification.

**Comment by yutang814** [comment]
![image](https://user-images.githubusercontent.com/74523125/159409209-4ffec29a-56ea-487c-b71e-e852a1606658.png)
Thanks! 
I have another question, the convolutional filters L in the figure, if I want to adjust L to 2, where should I modify it in the code?

**Comment by takh04** [comment]
No worries!
Yes, the number of layers L can't be easily modified, unlike other tunable parameters. 
Unfortunately, you will have to do this manually. If you look at **_QCNN.py_**, you can see the details of QCNN structure. You can increase the L by simply repeating the layers (which is by default set to 1). You need to use different weights (parameters) for the added layers, so you will have to multiply the total_params by L in **_Training.py_**
